#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = gnu.targets.arm.M3{1,0,4.9,3
#
ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/package/package_ti.drivers.om3g.dep
package/lib/lib/drivers_cc26x0r2/package/package_ti.drivers.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/package/package_ti.drivers.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/package/package_ti.drivers.om3g: package/package_ti.drivers.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/package/package_ti.drivers.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/package/package_ti.drivers.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/package/package_ti.drivers.sm3g: package/package_ti.drivers.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/package/package_ti.drivers.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/ADC.om3g.dep
package/lib/lib/drivers_cc26x0r2/ADC.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/ADC.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/ADC.om3g: ADC.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/ADC.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/ADC.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/ADC.sm3g: ADC.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/ADC.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/ADCBuf.om3g.dep
package/lib/lib/drivers_cc26x0r2/ADCBuf.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/ADCBuf.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/ADCBuf.om3g: ADCBuf.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/ADCBuf.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/ADCBuf.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/ADCBuf.sm3g: ADCBuf.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/ADCBuf.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/Camera.om3g.dep
package/lib/lib/drivers_cc26x0r2/Camera.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/Camera.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/Camera.om3g: Camera.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/Camera.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/Camera.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/Camera.sm3g: Camera.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/Camera.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/Capture.om3g.dep
package/lib/lib/drivers_cc26x0r2/Capture.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/Capture.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/Capture.om3g: Capture.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/Capture.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/Capture.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/Capture.sm3g: Capture.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/Capture.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/I2C.om3g.dep
package/lib/lib/drivers_cc26x0r2/I2C.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/I2C.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/I2C.om3g: I2C.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/I2C.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/I2C.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/I2C.sm3g: I2C.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/I2C.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/I2CSlave.om3g.dep
package/lib/lib/drivers_cc26x0r2/I2CSlave.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/I2CSlave.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/I2CSlave.om3g: I2CSlave.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/I2CSlave.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/I2CSlave.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/I2CSlave.sm3g: I2CSlave.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/I2CSlave.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/I2S.om3g.dep
package/lib/lib/drivers_cc26x0r2/I2S.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/I2S.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/I2S.om3g: I2S.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/I2S.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/I2S.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/I2S.sm3g: I2S.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/I2S.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/NVS.om3g.dep
package/lib/lib/drivers_cc26x0r2/NVS.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/NVS.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/NVS.om3g: NVS.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/NVS.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/NVS.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/NVS.sm3g: NVS.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/NVS.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/PWM.om3g.dep
package/lib/lib/drivers_cc26x0r2/PWM.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/PWM.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/PWM.om3g: PWM.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/PWM.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/PWM.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/PWM.sm3g: PWM.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/PWM.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/SDSPI.om3g.dep
package/lib/lib/drivers_cc26x0r2/SDSPI.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/SDSPI.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/SDSPI.om3g: SDSPI.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/SDSPI.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/SDSPI.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/SDSPI.sm3g: SDSPI.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/SDSPI.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/SD.om3g.dep
package/lib/lib/drivers_cc26x0r2/SD.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/SD.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/SD.om3g: SD.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/SD.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/SD.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/SD.sm3g: SD.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/SD.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/SDFatFS.om3g.dep
package/lib/lib/drivers_cc26x0r2/SDFatFS.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/SDFatFS.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/SDFatFS.om3g: SDFatFS.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/SDFatFS.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/SDFatFS.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/SDFatFS.sm3g: SDFatFS.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/SDFatFS.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/SPI.om3g.dep
package/lib/lib/drivers_cc26x0r2/SPI.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/SPI.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/SPI.om3g: SPI.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/SPI.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/SPI.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/SPI.sm3g: SPI.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/SPI.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/Timer.om3g.dep
package/lib/lib/drivers_cc26x0r2/Timer.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/Timer.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/Timer.om3g: Timer.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/Timer.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/Timer.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/Timer.sm3g: Timer.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/Timer.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/UART.om3g.dep
package/lib/lib/drivers_cc26x0r2/UART.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/UART.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/UART.om3g: UART.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/UART.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/UART.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/UART.sm3g: UART.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/UART.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/Watchdog.om3g.dep
package/lib/lib/drivers_cc26x0r2/Watchdog.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/Watchdog.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/Watchdog.om3g: Watchdog.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/Watchdog.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/Watchdog.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/Watchdog.sm3g: Watchdog.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/Watchdog.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./utils/List.om3g.dep
package/lib/lib/drivers_cc26x0r2/./utils/List.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./utils/List.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./utils/List.om3g: ./utils/List.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./utils/List.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./utils/List.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./utils/List.sm3g: ./utils/List.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./utils/List.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./utils/RingBuf.om3g.dep
package/lib/lib/drivers_cc26x0r2/./utils/RingBuf.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./utils/RingBuf.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./utils/RingBuf.om3g: ./utils/RingBuf.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./utils/RingBuf.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./utils/RingBuf.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./utils/RingBuf.sm3g: ./utils/RingBuf.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./utils/RingBuf.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./adc/ADCCC26XX.om3g.dep
package/lib/lib/drivers_cc26x0r2/./adc/ADCCC26XX.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./adc/ADCCC26XX.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./adc/ADCCC26XX.om3g: ./adc/ADCCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./adc/ADCCC26XX.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./adc/ADCCC26XX.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./adc/ADCCC26XX.sm3g: ./adc/ADCCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./adc/ADCCC26XX.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./adcbuf/ADCBufCC26XX.om3g.dep
package/lib/lib/drivers_cc26x0r2/./adcbuf/ADCBufCC26XX.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./adcbuf/ADCBufCC26XX.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./adcbuf/ADCBufCC26XX.om3g: ./adcbuf/ADCBufCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./adcbuf/ADCBufCC26XX.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./adcbuf/ADCBufCC26XX.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./adcbuf/ADCBufCC26XX.sm3g: ./adcbuf/ADCBufCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./adcbuf/ADCBufCC26XX.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./crypto/CryptoCC26XX.om3g.dep
package/lib/lib/drivers_cc26x0r2/./crypto/CryptoCC26XX.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./crypto/CryptoCC26XX.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./crypto/CryptoCC26XX.om3g: ./crypto/CryptoCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./crypto/CryptoCC26XX.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./crypto/CryptoCC26XX.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./crypto/CryptoCC26XX.sm3g: ./crypto/CryptoCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./crypto/CryptoCC26XX.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./dma/UDMACC26XX.om3g.dep
package/lib/lib/drivers_cc26x0r2/./dma/UDMACC26XX.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./dma/UDMACC26XX.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./dma/UDMACC26XX.om3g: ./dma/UDMACC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./dma/UDMACC26XX.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./dma/UDMACC26XX.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./dma/UDMACC26XX.sm3g: ./dma/UDMACC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./dma/UDMACC26XX.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./gpio/GPIOCC26XX.om3g.dep
package/lib/lib/drivers_cc26x0r2/./gpio/GPIOCC26XX.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./gpio/GPIOCC26XX.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./gpio/GPIOCC26XX.om3g: ./gpio/GPIOCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./gpio/GPIOCC26XX.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./gpio/GPIOCC26XX.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./gpio/GPIOCC26XX.sm3g: ./gpio/GPIOCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./gpio/GPIOCC26XX.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./i2c/I2CCC26XX.om3g.dep
package/lib/lib/drivers_cc26x0r2/./i2c/I2CCC26XX.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./i2c/I2CCC26XX.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./i2c/I2CCC26XX.om3g: ./i2c/I2CCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./i2c/I2CCC26XX.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./i2c/I2CCC26XX.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./i2c/I2CCC26XX.sm3g: ./i2c/I2CCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./i2c/I2CCC26XX.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./nvs/NVSCC26XX.om3g.dep
package/lib/lib/drivers_cc26x0r2/./nvs/NVSCC26XX.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./nvs/NVSCC26XX.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./nvs/NVSCC26XX.om3g: ./nvs/NVSCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./nvs/NVSCC26XX.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./nvs/NVSCC26XX.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./nvs/NVSCC26XX.sm3g: ./nvs/NVSCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./nvs/NVSCC26XX.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./pdm/Codec1.om3g.dep
package/lib/lib/drivers_cc26x0r2/./pdm/Codec1.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./pdm/Codec1.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./pdm/Codec1.om3g: ./pdm/Codec1.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./pdm/Codec1.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./pdm/Codec1.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./pdm/Codec1.sm3g: ./pdm/Codec1.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./pdm/Codec1.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX.om3g.dep
package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX.om3g: ./pdm/PDMCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX.sm3g: ./pdm/PDMCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX_util.om3g.dep
package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX_util.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX_util.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX_util.om3g: ./pdm/PDMCC26XX_util.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX_util.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX_util.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX_util.sm3g: ./pdm/PDMCC26XX_util.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX_util.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./pin/PINCC26XX.om3g.dep
package/lib/lib/drivers_cc26x0r2/./pin/PINCC26XX.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./pin/PINCC26XX.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./pin/PINCC26XX.om3g: ./pin/PINCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./pin/PINCC26XX.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./pin/PINCC26XX.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./pin/PINCC26XX.sm3g: ./pin/PINCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./pin/PINCC26XX.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX.om3g.dep
package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX.om3g: ./power/PowerCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX.sm3g: ./power/PowerCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX_calibrateRCOSC.om3g.dep
package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX_calibrateRCOSC.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX_calibrateRCOSC.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX_calibrateRCOSC.om3g: ./power/PowerCC26XX_calibrateRCOSC.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX_calibrateRCOSC.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX_calibrateRCOSC.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX_calibrateRCOSC.sm3g: ./power/PowerCC26XX_calibrateRCOSC.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX_calibrateRCOSC.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./pwm/PWMTimerCC26XX.om3g.dep
package/lib/lib/drivers_cc26x0r2/./pwm/PWMTimerCC26XX.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./pwm/PWMTimerCC26XX.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./pwm/PWMTimerCC26XX.om3g: ./pwm/PWMTimerCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./pwm/PWMTimerCC26XX.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./pwm/PWMTimerCC26XX.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./pwm/PWMTimerCC26XX.sm3g: ./pwm/PWMTimerCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./pwm/PWMTimerCC26XX.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./spi/SPICC26XXDMA.om3g.dep
package/lib/lib/drivers_cc26x0r2/./spi/SPICC26XXDMA.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./spi/SPICC26XXDMA.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./spi/SPICC26XXDMA.om3g: ./spi/SPICC26XXDMA.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./spi/SPICC26XXDMA.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./spi/SPICC26XXDMA.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./spi/SPICC26XXDMA.sm3g: ./spi/SPICC26XXDMA.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./spi/SPICC26XXDMA.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./timer/GPTimerCC26XX.om3g.dep
package/lib/lib/drivers_cc26x0r2/./timer/GPTimerCC26XX.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./timer/GPTimerCC26XX.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./timer/GPTimerCC26XX.om3g: ./timer/GPTimerCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./timer/GPTimerCC26XX.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./timer/GPTimerCC26XX.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./timer/GPTimerCC26XX.sm3g: ./timer/GPTimerCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./timer/GPTimerCC26XX.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./uart/UARTCC26XX.om3g.dep
package/lib/lib/drivers_cc26x0r2/./uart/UARTCC26XX.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./uart/UARTCC26XX.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./uart/UARTCC26XX.om3g: ./uart/UARTCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./uart/UARTCC26XX.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./uart/UARTCC26XX.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./uart/UARTCC26XX.sm3g: ./uart/UARTCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./uart/UARTCC26XX.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26x0r2/./watchdog/WatchdogCC26XX.om3g.dep
package/lib/lib/drivers_cc26x0r2/./watchdog/WatchdogCC26XX.om3g.dep: ;
endif

package/lib/lib/drivers_cc26x0r2/./watchdog/WatchdogCC26XX.om3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./watchdog/WatchdogCC26XX.om3g: ./watchdog/WatchdogCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL -I/db/vtree/library/trees/mcpi/mcpi-b14/exports/coresdk_cc13xx_cc26xx_3_01_00_14/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./watchdog/WatchdogCC26XX.om3g: export LD_LIBRARY_PATH=

package/lib/lib/drivers_cc26x0r2/./watchdog/WatchdogCC26XX.sm3g: | .interfaces
package/lib/lib/drivers_cc26x0r2/./watchdog/WatchdogCC26XX.sm3g: ./watchdog/WatchdogCC26XX.c lib/drivers_cc26x0r2.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -g  -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_9_3  -O2   -DDEVICE_FAMILY=cc26x0r2 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26x0r2/./watchdog/WatchdogCC26XX.sm3g: export LD_LIBRARY_PATH=

clean,m3g ::
	-$(RM) package/lib/lib/drivers_cc26x0r2/package/package_ti.drivers.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/ADC.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/ADCBuf.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/Camera.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/Capture.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/I2C.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/I2CSlave.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/I2S.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/NVS.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/PWM.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/SDSPI.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/SD.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/SDFatFS.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/SPI.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/Timer.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/UART.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/Watchdog.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./utils/List.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./utils/RingBuf.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./adc/ADCCC26XX.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./adcbuf/ADCBufCC26XX.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./crypto/CryptoCC26XX.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./dma/UDMACC26XX.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./gpio/GPIOCC26XX.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./i2c/I2CCC26XX.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./nvs/NVSCC26XX.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./pdm/Codec1.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX_util.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./pin/PINCC26XX.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX_calibrateRCOSC.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./pwm/PWMTimerCC26XX.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./spi/SPICC26XXDMA.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./timer/GPTimerCC26XX.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./uart/UARTCC26XX.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./watchdog/WatchdogCC26XX.om3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/package/package_ti.drivers.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/ADC.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/ADCBuf.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/Camera.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/Capture.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/I2C.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/I2CSlave.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/I2S.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/NVS.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/PWM.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/SDSPI.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/SD.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/SDFatFS.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/SPI.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/Timer.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/UART.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/Watchdog.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./utils/List.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./utils/RingBuf.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./adc/ADCCC26XX.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./adcbuf/ADCBufCC26XX.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./crypto/CryptoCC26XX.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./dma/UDMACC26XX.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./gpio/GPIOCC26XX.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./i2c/I2CCC26XX.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./nvs/NVSCC26XX.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./pdm/Codec1.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX_util.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./pin/PINCC26XX.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX_calibrateRCOSC.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./pwm/PWMTimerCC26XX.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./spi/SPICC26XXDMA.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./timer/GPTimerCC26XX.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./uart/UARTCC26XX.sm3g
	-$(RM) package/lib/lib/drivers_cc26x0r2/./watchdog/WatchdogCC26XX.sm3g

lib/drivers_cc26x0r2.am3g: package/lib/lib/drivers_cc26x0r2/package/package_ti.drivers.om3g package/lib/lib/drivers_cc26x0r2/ADC.om3g package/lib/lib/drivers_cc26x0r2/ADCBuf.om3g package/lib/lib/drivers_cc26x0r2/Camera.om3g package/lib/lib/drivers_cc26x0r2/Capture.om3g package/lib/lib/drivers_cc26x0r2/I2C.om3g package/lib/lib/drivers_cc26x0r2/I2CSlave.om3g package/lib/lib/drivers_cc26x0r2/I2S.om3g package/lib/lib/drivers_cc26x0r2/NVS.om3g package/lib/lib/drivers_cc26x0r2/PWM.om3g package/lib/lib/drivers_cc26x0r2/SDSPI.om3g package/lib/lib/drivers_cc26x0r2/SD.om3g package/lib/lib/drivers_cc26x0r2/SDFatFS.om3g package/lib/lib/drivers_cc26x0r2/SPI.om3g package/lib/lib/drivers_cc26x0r2/Timer.om3g package/lib/lib/drivers_cc26x0r2/UART.om3g package/lib/lib/drivers_cc26x0r2/Watchdog.om3g package/lib/lib/drivers_cc26x0r2/./utils/List.om3g package/lib/lib/drivers_cc26x0r2/./utils/RingBuf.om3g package/lib/lib/drivers_cc26x0r2/./adc/ADCCC26XX.om3g package/lib/lib/drivers_cc26x0r2/./adcbuf/ADCBufCC26XX.om3g package/lib/lib/drivers_cc26x0r2/./crypto/CryptoCC26XX.om3g package/lib/lib/drivers_cc26x0r2/./dma/UDMACC26XX.om3g package/lib/lib/drivers_cc26x0r2/./gpio/GPIOCC26XX.om3g package/lib/lib/drivers_cc26x0r2/./i2c/I2CCC26XX.om3g package/lib/lib/drivers_cc26x0r2/./nvs/NVSCC26XX.om3g package/lib/lib/drivers_cc26x0r2/./pdm/Codec1.om3g package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX.om3g package/lib/lib/drivers_cc26x0r2/./pdm/PDMCC26XX_util.om3g package/lib/lib/drivers_cc26x0r2/./pin/PINCC26XX.om3g package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX.om3g package/lib/lib/drivers_cc26x0r2/./power/PowerCC26XX_calibrateRCOSC.om3g package/lib/lib/drivers_cc26x0r2/./pwm/PWMTimerCC26XX.om3g package/lib/lib/drivers_cc26x0r2/./spi/SPICC26XXDMA.om3g package/lib/lib/drivers_cc26x0r2/./timer/GPTimerCC26XX.om3g package/lib/lib/drivers_cc26x0r2/./uart/UARTCC26XX.om3g package/lib/lib/drivers_cc26x0r2/./watchdog/WatchdogCC26XX.om3g lib/drivers_cc26x0r2.am3g.mak

clean::
	-$(RM) lib/drivers_cc26x0r2.am3g.mak
